const STATUS_ACTIVE = 1;
const STATUS_INACTIVE = 0;
const STATUS_SELLER_PENDING_TO_ACCEPT = 2;
const STATUS_COMISSIONIST_PENDING_TO_ACEEPT = 3;
const CAN_GO_HOME = 1;
const CAN_NOT_GO_HOME = 0;
const ROLE_ADMIN = 1;
const ROLE_SELLER = 2;
const ROLE_CLIENT = 3;
const ROLE_RESELLER = 4;

const PROMOTION_TYPE_SHIPPING = 1;
const PROMOTION_TYPE_FIXED_AMOUNT = 2;
const Roles = {
    admin: ROLE_ADMIN,
    seller: ROLE_SELLER
}
export {
    Roles,
    PROMOTION_TYPE_FIXED_AMOUNT,
    PROMOTION_TYPE_SHIPPING,
    ROLE_SELLER,
    ROLE_CLIENT,
    ROLE_RESELLER,
    ROLE_ADMIN,
    STATUS_COMISSIONIST_PENDING_TO_ACEEPT,
    STATUS_SELLER_PENDING_TO_ACCEPT,
    CAN_GO_HOME,
    CAN_NOT_GO_HOME,
    STATUS_ACTIVE,
    STATUS_INACTIVE
}